[package]
name = "crv"
version.workspace = true
edition.workspace = true

[[bin]]
name = "crv"
path = "src/main.rs"

[dependencies]
tokio.workspace = true
axum.workspace = true
tower.workspace = true
tower-http.workspace = true
clap.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
chrono.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
rusqlite.workspace = true
dotenvy.workspace = true
dirs.workspace = true
sha2.workspace = true
hex.workspace = true
bytes.workspace = true
rpassword.workspace = true
walkdir = "2"
crv-shared.workspace = true
