name: Rust CI & Release

on:
  push:
    branches: [ "main" ]
    tags: [ "v*.*.*" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build & Test (matrix)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build (Release)
        run: |
          cargo build --release -p crv-cli -p crv-edge -p crv-hive

      - name: Run tests (workspace)
        run: |
          cargo test --workspace --release --all-features --verbose

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: chronoverse-${{ runner.os }}-release
          path: |
            target/release/crv-cli*
            target/release/crv-edge*
            target/release/crv-hive*
          if-no-files-found: error
          compression-level: 6
          retention-days: 14

  release:
    name: Release on tag (matrix)
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: chronoverse-${{ runner.os }}-release
          path: dist/

      - name: Rename binaries with OS suffix
        shell: bash
        run: |
          set -euo pipefail
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            if [[ -f "dist/crv-cli.exe" ]]; then mv dist/crv-cli.exe dist/crv-cli-${{ runner.os }}.exe; fi
            if [[ -f "dist/crv-edge.exe" ]]; then mv dist/crv-edge.exe dist/crv-edge-${{ runner.os }}.exe; fi
            if [[ -f "dist/crv-hive.exe" ]]; then mv dist/crv-hive.exe dist/crv-hive-${{ runner.os }}.exe; fi
          else
            if [[ -f "dist/crv-cli" ]]; then mv dist/crv-cli dist/crv-cli-${{ runner.os }}; fi
            if [[ -f "dist/crv-edge" ]]; then mv dist/crv-edge dist/crv-edge-${{ runner.os }}; fi
            if [[ -f "dist/crv-hive" ]]; then mv dist/crv-hive dist/crv-hive-${{ runner.os }}; fi
          fi

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
